# 2주차 Day2[인공지능 수학 - 미적분] 실습

## 스칼라, 벡터, 행렬, 그리고 텐서: 계층구조 이해하기

In [1]:
import numpy as np

### 스칼라

In [2]:
s = 3

print("a:", s)
print(np.shape(s))

a: 3
()


In [3]:
# 스칼라를 벡터로 변환
a = np.reshape(s, (1,))

print("a:", a)
print(np.shape(a))

a: [3]
(1,)


In [4]:
# 스칼라를 행렬로 변환
a = np.reshape(s, (1,1))

print("a:", a)
print(np.shape(a))

a: [[3]]
(1, 1)


In [5]:
# 스칼라를 3-텐서로 변환
a = np.reshape(s, (1,1,1))

print("a:", a)
print(np.shape(a))

a: [[[3]]]
(1, 1, 1)


### 벡터

In [6]:
# 24-벡터
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

print("a:", a)
print(np.shape(a))

a: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)


In [7]:
# 24-벡터 --> (1x24) 행렬
A = a.reshape(1,24)

print("A:", A)
print("A:", np.shape(A))

A: [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]]
A: (1, 24)


In [8]:
# 24-벡터 --> (3x8) 행렬
A = a.reshape(3,8)

print("A:", A)
print("A:", np.shape(A))

A: [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
A: (3, 8)


In [9]:
# 24-벡터 --> (6x4) 행렬
A = a.reshape(6,4)

print("A:", A)
print("A:", np.shape(A))

A: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
A: (6, 4)


In [10]:
# 24-벡터 --> (24x1) 행렬
A = a.reshape(24,1)

print("A:", A)
print("A:", np.shape(A))

A: [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]
A: (24, 1)


In [11]:
# 24-벡터 --> (2x3x4) 텐서 (즉, 2개의 (3x4)행렬)
A = a.reshape(2, 3, 4)

print("A:", A)
print("A:", np.shape(A))

A: [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
A: (2, 3, 4)


In [12]:
# 벡터 --> 스칼라 (X)
## error: 벡터 a가 하나의 entry로 되어 있지 않기 때문에 아래의 경우는 모두 에러
# s = np.reshape(a, ())
# s = a.item()            

s = a[0]
print(s)

s = a.sum()
print(s)

1
300


### 행렬

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9,], [10, 11, 12]])

print(A)
print(np.shape(A))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [14]:
# 행렬 --> 3-텐서

#
T = A.reshape(1, 4, 3)

print(T)
print(np.shape(T))

#
T = A.reshape(2, 2, 3)

print(T)
print(np.shape(T))

#
T = A.reshape(2, 3, 2)

print(T)
print(np.shape(T))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
(1, 4, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [15]:
# 행렬 --> 벡터
a = A.reshape(12,)

print(a)
print(np.shape(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [16]:
#행렬 --> 스칼라

#
s = A[0,0]

print(s)
print(np.shape(s))

#
s = np.sum(A)

print(s)
print(np.shape(s))

1
()
78
()


### 텐서
스칼라, 벡터, 행렬을 아우르는 개념으로 숫자가 늘어설 수 있는 방향이 k개면 k-텐서로 부른다.

In [17]:
T = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9,], [10, 11, 12]]])

print(T)
print(np.shape(T))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [18]:
# 3-텐서 --> 행렬
A = T.reshape(4, 3)

print(A)
print(np.shape(A))

A = T.reshape(3, 4)

print(A)
print(np.shape(A))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [19]:
# 3-텐서 --> 벡터
a = T.reshape(12,)

print(a)
print(np.shape(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [20]:
# 3-텐서 --> 스칼라
s = T.sum()

print(s)
print(np.shape(s))

78
()
