# 2주차 Day2[인공지능 수학 - 미적분] 실습

## LU 분해(가우스 소거법)

In [1]:
import numpy as np
import scipy
import scipy.linalg

In [2]:
# 행렬 A, 벡터 b 코딩
A = np.array([[3, 1, 1], [1, -2, -1], [1, 1, 1]])
b = np.array([4, 1, 2])

print("A:", A)
print(np.shape(A))

print("b:", b)
print(np.shape(b))

A: [[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)
b: [4 1 2]
(3,)


In [3]:
# LU 분해의 결과를 각각 행렬로서 확인하기
P, L, U = scipy.linalg.lu(A)

print("P:", P)
print("L:", L)
print("U:", U)

AA = P @ L @ U
print("AA:", AA)

P: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L: [[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.33333333 -0.28571429  1.        ]]
U: [[ 3.          1.          1.        ]
 [ 0.         -2.33333333 -1.33333333]
 [ 0.          0.          0.28571429]]
AA: [[ 3.  1.  1.]
 [ 1. -2. -1.]
 [ 1.  1.  1.]]


In [4]:
# LU분해를 이용해 선형시스템 Ax = b 풀기
lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print("x:", x)
print(np.shape(x))

bb = A @ x
print("bb:", bb)

x: [ 1. -1.  2.]
(3,)
bb: [4. 1. 2.]


## 행렬의 Rank 계산하기
행렬의 rank: 이 행렬의 열들로 생성될 수 있는 벡터 공간의 차원(선형 독립인 열들의 최대 개수)

In [5]:
# rank=2인 2x2 행렬 A
A = np.array([[1, 3], [-2, 1]])
print("A:", A)

A: [[ 1  3]
 [-2  1]]


In [6]:
print("rank:", np.linalg.matrix_rank(A))
A_inv = np.linalg.inv(A)

print(A_inv)

rank: 2
[[ 0.14285714 -0.42857143]
 [ 0.28571429  0.14285714]]


In [7]:
# rank=1인 2x2 행렬 A
A = np.array([[1, 3], [2, 6]])
print("A:", A)

A: [[1 3]
 [2 6]]


In [8]:
print("rank:", np.linalg.matrix_rank(A))
A_inv = np.linalg.inv(A)

rank: 1


LinAlgError: Singular matrix

In [9]:
# LU 분해의 결과를 각각 행렬로서 확인하기
P, L, U = scipy.linalg.lu(A)

print("P:", P)
print("L:", L)
print("U:", U)

AA = P @ L @ U
print("AA:", AA)

P: [[0. 1.]
 [1. 0.]]
L: [[1.  0. ]
 [0.5 1. ]]
U: [[2. 6.]
 [0. 0.]]
AA: [[1. 3.]
 [2. 6.]]


In [10]:
b = np.array([2, 4])
# LU 분해
lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print("x:", x)
print(np.shape(x))

x: [nan nan]
(2,)


<ipython-input-10-8798edbb8efc>:3: LinAlgWarning: Diagonal number 2 is exactly zero. Singular matrix.
  lu, piv = scipy.linalg.lu_factor(A)
